### PR TITLE
fix: unique `key` error

### LINKED ISSUE #942: Warning: Each child in a list should have a unique "key" prop.
### What version of `million` are you using?

3.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

bun, yarn

### What operating system are you using?

wsl

### What browser are you using?

edge, chrome

### Describe the Bug

create fresh vite using bun or yarn
install millionjs using bun or yarn

followed the instructions 

```ts
export default defineConfig({
  plugins: [million.vite({ auto: true }), react()],
});
```

then I do.. bun run dev.

look at the console.
 
image

### What's the expected result?

expected result is to show non of that error at all because its a fresh project. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-ya4ek3

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lxsmnsyc**
Fixes the unintentional unique `key` error thrown by React because of `block`

- Fixes #942

### CODE REVIEW

File: packages/react/block.ts [hunk 1]
```diff
@@ -65,17 +65,14 @@ export const block = <P extends MillionProps>(
...
     for (let i = 0; i < childrenSize; ++i) {
-      children[i + 2] = portalRef.current[i]?.portal;
+      children[i] = portalRef.current[i]?.portal;
     }
 
-    const vnode = createElement(Fragment, { children });
+    const vnode = createElement(Fragment, {}, marker, createElement(Effect, {
+      effect,
+      deps: hmrTimestamp ? [hmrTimestamp] : [],
+    }), children);
```
Comment (Aslemammad) [inline packages/react/block.ts:75]: is it possible that portals (children) won't have a key and the warning would be shown again?

What I'd suggest is that you spread the children by `, ...children`, so this way the whole error would be removed. 

```
}), ...children);
```

Comment (lxsmnsyc) [reply packages/react/block.ts:75]: spreading might hit the arguments bound because it has a lower bound than arrays.
